#!/usr/bin/env python3
import json
from pathlib import Path
from datetime import date, timedelta

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/itinerary.json"
DATA.parent.mkdir(parents=True, exist_ok=True)

hotels = {
  "vancouver": [
    {"name":"Fairmont Pacific Rim","type":"city hotel","why":"Best downtown splurge; walkable to waterfront, Gastown and Stanley Park.","url":"https://www.fairmont.com/pacific-rim-vancouver/","book":"https://www.google.com/travel/search?q=Fairmont%20Pacific%20Rim%20Vancouver"},
    {"name":"OPUS Vancouver","type":"boutique hotel","why":"Compact Yaletown base with restaurants and SkyTrain access.","url":"https://www.opushotel.com/","book":"https://www.google.com/travel/search?q=OPUS%20Vancouver"},
    {"name":"Westin Wall Centre Vancouver Airport","type":"airport hotel","why":"Richmond base with airport shuttle, pool and easy McArthurGlen access.","url":"https://www.marriott.com/en-us/hotels/yvrwc-the-westin-wall-centre-vancouver-airport/overview/","book":"https://www.google.com/travel/search?q=Westin%20Wall%20Centre%20Vancouver%20Airport"},
    {"name":"Airbnb Vancouver search","type":"vacation rental","why":"Search downtown, Yaletown, Coal Harbour or Richmond by exact dates.","url":"https://www.airbnb.com/vancouver-canada/stays","book":"https://www.airbnb.com/vancouver-canada/stays"}
  ],
  "whistler": [
    {"name":"Whistler Village hotel search","type":"village hotel","why":"Keep the car parked and walk to restaurants, lifts and the village promenade.","url":"https://www.whistler.com/activities/","book":"https://www.google.com/travel/search?q=Whistler%20Village%20hotel"},
    {"name":"Whistler Airbnb search","type":"vacation rental","why":"Search Village North or Upper Village for a kitchen and quieter evening.","url":"https://www.airbnb.com/whistler-canada/stays","book":"https://www.airbnb.com/whistler-canada/stays"}
  ],
  "kamloops": [
    {"name":"Delta Hotels Kamloops","type":"city hotel","why":"Central base with full-service hotel convenience after the long interior drive.","url":"https://www.marriott.com/en-us/hotels/ykade-delta-hotels-kamloops/overview/","book":"https://www.google.com/travel/search?q=Delta%20Hotels%20Kamloops"},
    {"name":"Hampton Inn Kamloops","type":"hotel","why":"Practical chain option for breakfast, parking and a simple reset.","url":"https://www.hilton.com/en/hotels/kambchx-hampton-kamloops/","book":"https://www.google.com/travel/search?q=Hampton%20Inn%20Kamloops"},
    {"name":"Coast Kamloops Hotel","type":"hotel","why":"Pool, hot tub, parking and highway-friendly location.","url":"https://mundihotels.ca/properties/","book":"https://www.google.com/travel/search?q=Coast%20Kamloops%20Hotel"},
    {"name":"Airbnb Kamloops search","type":"vacation rental","why":"Search a suite with parking if you prefer a kitchen on the road.","url":"https://www.airbnb.com/kamloops-canada/stays","book":"https://www.airbnb.com/kamloops-canada/stays"}
  ],
  "revelstoke": [
    {"name":"Basecamp Resorts Revelstoke","type":"suite / condo","why":"Full-kitchen style base with hot-tub options and room to decompress.","url":"https://basecampresorts.com/destinations/revelstoke/","book":"https://www.google.com/travel/search?q=Basecamp%20Resorts%20Revelstoke"},
    {"name":"Regent Hotel Revelstoke","type":"town hotel","why":"Downtown location for a short overnight and dinner on foot.","url":"https://www.regentrevelstoke.com/","book":"https://www.google.com/travel/search?q=Regent%20Hotel%20Revelstoke"},
    {"name":"Stoke Hotel","type":"hotel","why":"Value-oriented highway option with practical parking.","url":"https://www.stokehotel.ca/","book":"https://www.google.com/travel/search?q=Stoke%20Hotel%20Revelstoke"},
    {"name":"Airbnb Revelstoke search","type":"vacation rental","why":"Search cabins, suites or hot-tub stays near town or the mountain.","url":"https://www.airbnb.com/revelstoke-canada/stays","book":"https://www.airbnb.com/revelstoke-canada/stays"}
  ],
  "golden": [
    {"name":"Golden hotel search","type":"town hotel","why":"Useful alternative if Lake Louise or Field inventory is tight.","url":"https://www.tourismgolden.com/","book":"https://www.google.com/travel/search?q=Golden%20BC%20hotel"},
    {"name":"Airbnb Golden cabin search","type":"cabin / rental","why":"Look for a private cabin with a kitchen and mountain view near Golden.","url":"https://www.airbnb.com/golden-canada/stays","book":"https://www.airbnb.com/golden-canada/stays"}
  ],
  "lake-louise": [
    {"name":"Baker Creek by Basecamp","type":"romantic cabin base","why":"Strongest all-round base: log cabins, creekside fire pits, café, sauna and Bow Valley Parkway location.","url":"https://www.basecampresorts.com/bakercreek","book":"https://www.basecampresorts.com/bakercreek"},
    {"name":"Storm Mountain Lodge","type":"unplugged historic cabin","why":"Romantic historic log cabins, wood-burning fireplaces and on-site dining. No Wi-Fi, TV or kitchen.","url":"https://stormmountainlodge.com/logcabins","book":"https://us2.cloudbeds.com/reservation/uc9zZn"},
    {"name":"Emerald Lake Lodge","type":"lake lodge splurge","why":"One-night electronics-lite lake stay with fireplaces and cabin-style buildings.","url":"https://crmr.com/resorts/emerald-lake/accommodations/","book":"https://bookings.travelclick.com/115058"},
    {"name":"Paradise Lodge & Bungalows","type":"Lake Louise cabin","why":"Cabins and suites near the lake, with guest shuttle and e-bike options.","url":"https://www.paradiselodge.com/","book":"https://www.paradiselodge.com/"},
    {"name":"Airbnb Lake Louise search","type":"vacation rental","why":"Limited inventory. Also search Field, Golden and Canmore for more choice.","url":"https://www.airbnb.com/lake-louise-canada/stays","book":"https://www.airbnb.com/lake-louise-canada/stays"}
  ],
  "jasper": [
    {"name":"Jasper accommodation directory","type":"hotel directory","why":"Check operating status after the 2024 wildfire before booking.","url":"https://jasper.travel/accommodations","book":"https://jasper.travel/accommodations"},
    {"name":"Jasper Inn & Suites","type":"hotel","why":"Quiet town base listed by Tourism Jasper.","url":"https://jasper.travel/accommodations/jasper-inn-suites/","book":"https://www.google.com/travel/search?q=Jasper%20Inn%20Suites"},
    {"name":"Fairmont Jasper Park Lodge","type":"lodge / cabins","why":"Large lakeside lodge experience with individual cabins and resort amenities.","url":"https://jasper.travel/accommodations/fairmont-jasper-park-lodge/","book":"https://www.google.com/travel/search?q=Fairmont%20Jasper%20Park%20Lodge"},
    {"name":"Bear Hill Lodge","type":"cabins","why":"Cabin feel close to town. Verify 2026 operating status and availability.","url":"https://jasper.travel/accommodations/bear-hill-lodge/","book":"https://www.google.com/travel/search?q=Bear%20Hill%20Lodge%20Jasper"},
    {"name":"Airbnb Jasper search","type":"vacation rental","why":"Search Jasper, Hinton and Jasper Lake if town inventory is constrained.","url":"https://www.airbnb.com/jasper-canada/stays","book":"https://www.airbnb.com/jasper-canada/stays"}
  ],
  "banff-canmore": [
    {"name":"The Juniper Hotel & Bistro","type":"Banff hotel / forest cabins","why":"Panoramic valley views, parking, shuttle and a strong couples fit.","url":"https://thejuniper.com/","book":"https://thejuniper.com/all-rooms/"},
    {"name":"Canmore accommodation directory","type":"hotel directory","why":"More inventory and often better value than Banff townsite.","url":"https://www.explorecanmore.ca/all-accommodations","book":"https://www.explorecanmore.ca/all-accommodations"},
    {"name":"Coast Canmore Hotel","type":"hotel","why":"Pool, hot tub, parking and a practical road-trip base.","url":"https://www.coasthotels.com/coast-canmore-hotel-and-conference-centre","book":"https://www.google.com/travel/search?q=Coast%20Canmore%20Hotel"},
    {"name":"Airbnb Banff search","type":"vacation rental","why":"Search Banff, Canmore or Dead Man's Flats; check parking and park access.","url":"https://www.airbnb.com/banff-canada/stays","book":"https://www.airbnb.com/banff-canada/stays"}
  ],
  "yvr": [
    {"name":"Westin Wall Centre Vancouver Airport","type":"airport hotel","why":"Airport shuttle, Richmond location and McArthurGlen access.","url":"https://www.marriott.com/en-us/hotels/yvrwc-the-westin-wall-centre-vancouver-airport/overview/","book":"https://www.google.com/travel/search?q=Westin%20Wall%20Centre%20Vancouver%20Airport"},
    {"name":"Holiday Inn Vancouver Airport Richmond","type":"airport hotel","why":"Airport shuttle, parking, restaurant and simple final-night logistics.","url":"https://www.ihg.com/holidayinn/hotels/us/en/richmond/yvrap/hoteldetail","book":"https://www.google.com/travel/search?q=Holiday%20Inn%20Vancouver%20Airport%20Richmond"},
    {"name":"Residence Inn Vancouver Airport","type":"airport hotel / kitchen","why":"In-room kitchens and complimentary airport shuttle listed by Marriott.","url":"https://www.marriott.com/en-us/hotels/yvrra-residence-inn-vancouver-airport/overview/","book":"https://www.google.com/travel/search?q=Residence%20Inn%20Vancouver%20Airport"}
  ]
}

activities = {
  "vancouver": ["Stanley Park seawall", "Granville Island Public Market", "Gastown and waterfront", "McArthurGlen Designer Outlet", "Steveston village if energy allows"],
  "whistler": ["Sea-to-Sky viewpoints", "Shannon Falls", "Sea to Sky Gondola", "Whistler Village", "PEAK 2 PEAK if operating and weather allows"],
  "kamloops": ["Riverside Park", "Thompson River sunset", "Kamloops local dinner", "Optional Sun Peaks detour only if schedule allows"],
  "revelstoke": ["Mount Revelstoke National Park", "Giant Cedars boardwalk", "Meadows in the Sky Parkway if open", "Revelstoke Railway Museum", "Rogers Pass viewpoints"],
  "yoho": ["Emerald Lake loop", "Natural Bridge", "Takakkaw Falls if road is open", "Field village", "Kicking Horse viewpoints"],
  "lake-louise": ["Lake Louise lakeshore", "Moraine Lake via reserved shuttle", "Bow Valley Parkway", "Johnston Canyon if open", "Cabin fire and slow evening"],
  "icefields": ["Bow Lake", "Peyto Lake", "Waterfowl Lakes", "Mistaya Canyon", "Weeping Wall", "Columbia Icefield", "Athabasca Glacier viewpoint", "Sunwapta Falls", "Athabasca Falls"],
  "jasper": ["Pyramid Lake and Pyramid Island", "Patricia Lake", "Lac Beauvert", "Jasper SkyTram if open", "Maligne Lake and Spirit Island cruise if operating", "Jasper townsite"],
  "banff": ["Banff Avenue", "Bow Falls", "Banff Gondola", "Upper Hot Springs", "Johnston Canyon", "Canmore arts and cafés", "Lake Minnewanka if time"],
  "return": ["Rogers Pass", "Revelstoke coffee and riverfront", "Hope or Merritt rest stop", "YVR hotel reset", "McArthurGlen final shop"]
}

# Full one-hour grid. Each day gets a practical block for every hour 06:00 to 23:00.
def grid_for(day_label, date_s, base, route, focus, overnight, overrides):
    blocks=[]
    for h in range(6,24):
        key=f"{h:02d}:00"
        blocks.append({"time":key,"title":"Open / flexible","detail":"Keep this hour uncommitted for meals, weather, parking, queues or a spontaneous stop.","kind":"buffer"})
    by={b["time"]:b for b in blocks}
    for t,title,detail,kind in overrides:
        by[t]={"time":t,"title":title,"detail":detail,"kind":kind}
    return {"date":date_s,"label":day_label,"base":base,"route":route,"focus":focus,"overnight":overnight,"blocks":[by[f"{h:02d}:00"] for h in range(6,24)]}

plans=[]
def add(label, ds, base, route, focus, overnight, overrides):
    plans.append(grid_for(label, ds, base, route, focus, overnight, overrides))

add("Day 1 · Arrival + airport outlet", "2026-09-23", "Vancouver / Richmond", "YVR → McArthurGlen → downtown or YVR hotel", "Land softly. Shop only if energy and baggage logistics allow.", "Vancouver or Richmond", [
("06:00","Arrival buffer","Flight arrival time is unknown. Keep this as airport, immigration and baggage buffer.","travel"),("07:00","Arrival + immigration","Collect bags, get coffee and check rental-car timing.","travel"),("08:00","Transfer to hotel or outlet","McArthurGlen is beside YVR and connected by Canada Line. Leave bags in hotel or use confirmed luggage storage.","travel"),("09:00","Outlet opening buffer","Confirm same-day hours before committing. Official and tourism listings show around 10:00 opening, with seasonal variation.","shop"),("10:00","McArthurGlen Designer Outlet","Outdoor village, 80+ brands and airport convenience. Set a 2-hour cap today.","shop"),("11:00","Outlet lunch / coffee","Keep receipts and check baggage capacity before buying bulky items.","food"),("12:00","Transfer and check-in","Take Canada Line or hotel shuttle. Do not force downtown sightseeing after a long flight.","travel"),("13:00","Hotel reset","Shower, nap, hydrate.","rest"),("14:00","Hotel reset","Keep this hour unplanned.","rest"),("15:00","Easy neighbourhood walk","Richmond riverfront or downtown waterfront depending on hotel.","walk"),("16:00","Stanley Park or Richmond option","Choose one only if alert. Otherwise rest.","walk"),("17:00","Dinner","Early dinner near the hotel.","food"),("18:00","Dinner / settle","No major reservation required.","food"),("19:00","Light planning","Confirm tomorrow's city plan and any outlet receipts.","plan"),("20:00","Wind down","Prepare for time-zone adjustment.","rest"),("21:00","Sleep","Aim for an early night.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 2 · Vancouver city", "2026-09-24", "Vancouver", "Downtown loop on foot / transit", "Use the only full city day for the iconic waterfront and market rhythm.", "Vancouver", [
("06:00","Slow breakfast","Start easy after arrival day.","food"),("07:00","Stanley Park seawall","Early walk or cycle before crowds.","walk"),("08:00","Stanley Park","Totem poles, Coal Harbour edge and forest loop.","walk"),("09:00","Stanley Park","Finish at Second Beach or the seawall.","walk"),("10:00","Transit to Granville Island","Allow for transit and queue time.","travel"),("11:00","Granville Island Public Market","Market browsing and early lunch.","food"),("12:00","Granville Island","Studios, shops and waterfront.","explore"),("13:00","False Creek walk","Aquabus or walk toward Yaletown.","walk"),("14:00","Yaletown / waterfront","Flexible city hour.","explore"),("15:00","Gastown","Water Street, galleries and coffee.","explore"),("16:00","Canada Place","Waterfront views and hotel return.","walk"),("17:00","Rest / dress","Protect energy for dinner.","rest"),("18:00","Dinner","Book one neighbourhood restaurant, not a cross-city plan.","food"),("19:00","Dinner","Slow evening.","food"),("20:00","Pack for road start","Rental car documents, layers, snacks.","plan"),("21:00","Sleep","Tomorrow begins with Sea-to-Sky.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 3 · Sea-to-Sky to Whistler", "2026-09-25", "Whistler", "Vancouver → Horseshoe Bay → Squamish → Whistler", "Scenic highway day. Do not treat the 2-hour baseline as the whole day.", "Whistler Village", [
("06:00","Breakfast + check-out","Pick up rental car after breakfast.","travel"),("07:00","Collect car","Inspect tires, winter-tire policy and roadside cover.","travel"),("08:00","Drive to Horseshoe Bay","Leave Vancouver before the city builds.","travel"),("09:00","Howe Sound viewpoint","Short stop near Horseshoe Bay.","stop"),("10:00","Drive to Shannon Falls","Follow Highway 99 north.","travel"),("11:00","Shannon Falls + Sea to Sky Gondola","Choose the gondola only if weather and tickets cooperate.","explore"),("12:00","Squamish lunch","Eat before the next stretch.","food"),("13:00","Drive toward Whistler","Stop at Brandywine Falls if open and time allows.","travel"),("14:00","Brandywine Falls / viewpoints","Short walk, no ambitious hike.","explore"),("15:00","Arrive Whistler","Check in and park the car.","travel"),("16:00","Whistler Village","Pedestrian village walk.","explore"),("17:00","Whistler Village","Flexible shopping or café.","explore"),("18:00","Dinner","Village dinner.","food"),("19:00","Dinner","Keep the evening simple.","food"),("20:00","Plan Duffy Lake leg","Check DriveBC and daylight conditions.","plan"),("21:00","Sleep","Tomorrow is a long scenic transfer.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 4 · Whistler to Kamloops", "2026-09-26", "Kamloops", "Whistler → Pemberton → Duffey Lake → Lillooet → Cache Creek → Kamloops", "The scenic interior route is longer and more weather-sensitive than the direct highway route.", "Kamloops", [
("06:00","Breakfast","Pack snacks and water.","food"),("07:00","Check road conditions","DriveBC check before Duffey Lake Road.","plan"),("08:00","Whistler → Pemberton","Mountain and valley views.","travel"),("09:00","Pemberton coffee / fuel","Fuel before the remote stretch.","stop"),("10:00","Duffey Lake Road","Slow scenic drive. Watch for wildlife and weather.","travel"),("11:00","Duffey Lake viewpoint","Short photo stop.","stop"),("12:00","Duffey Lake / Seton area","Continue with no rushed hike.","travel"),("13:00","Lillooet lunch","Refuel and take a proper break.","food"),("14:00","Lillooet to Cache Creek","Interior landscape change.","travel"),("15:00","Cache Creek stop","Coffee, fuel and route check.","stop"),("16:00","Drive to Kamloops","Final road leg.","travel"),("17:00","Drive to Kamloops","Arrive buffer.","travel"),("18:00","Check-in","Reset at hotel.","rest"),("19:00","Dinner","Early meal.","food"),("20:00","Dinner / tomorrow prep","Confirm Revelstoke reservation and weather.","plan"),("21:00","Sleep","Long drive complete.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 5 · Kamloops to Revelstoke", "2026-09-27", "Revelstoke", "Kamloops → Salmon Arm → Craigellachie → Revelstoke", "A manageable eastbound day with lake and railway-history stops.", "Revelstoke", [
("06:00","Breakfast","Simple hotel breakfast.","food"),("07:00","Check out + fuel","Start before the highway fills.","travel"),("08:00","Drive toward Salmon Arm","Shuswap scenery.","travel"),("09:00","Salmon Arm waterfront","Coffee and short walk.","stop"),("10:00","Drive to Sicamous","Lake country.","travel"),("11:00","Sicamous stop","Fuel and stretch.","stop"),("12:00","Drive to Craigellachie","Follow Trans-Canada.","travel"),("13:00","Last Spike, Craigellachie","Short railway-history stop and lunch snack.","explore"),("14:00","Drive to Revelstoke","Mountain route.","travel"),("15:00","Arrive Revelstoke","Check in.","travel"),("16:00","Revelstoke town","Railway museum or riverfront if open.","explore"),("17:00","Revelstoke town","Coffee, groceries and dinner supplies.","food"),("18:00","Dinner","Town dinner.","food"),("19:00","Rest","Tomorrow's park road is daylight dependent.","rest"),("20:00","Check Parks Canada updates","Mount Revelstoke and Rogers Pass conditions.","plan"),("21:00","Sleep","Overnight recovery.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 6 · Revelstoke to Golden and Yoho", "2026-09-28", "Golden or Field", "Revelstoke → Rogers Pass → Golden → Yoho → Emerald Lake", "Prioritize one park walk and arrive at the cabin base before dark.", "Golden / Field / Emerald Lake area", [
("06:00","Breakfast","Early start for mountain light.","food"),("07:00","Mount Revelstoke option","Meadows in the Sky Parkway only if open and weather-safe.","explore"),("08:00","Mount Revelstoke / Giant Cedars","Choose one. Do not force both.","explore"),("09:00","Return to Trans-Canada","Fuel and leave Revelstoke.","travel"),("10:00","Rogers Pass","Glacier viewpoints and short walks.","explore"),("11:00","Rogers Pass","Keep the stop weather-flexible.","explore"),("12:00","Golden lunch","Town lunch and fuel.","food"),("13:00","Golden to Yoho","Enter Yoho on Highway 1.","travel"),("14:00","Natural Bridge","Short stop near Emerald Lake.","explore"),("15:00","Emerald Lake","Lakeshore loop start or canoe if operating.","explore"),("16:00","Emerald Lake","Finish loop and check lodge / cabin timing.","explore"),("17:00","Check-in","Golden, Field or Emerald Lake accommodation.","travel"),("18:00","Dinner","Reserve in advance if staying at Storm or Emerald.","food"),("19:00","Fireplace / slow evening","Cabin night.","rest"),("20:00","Plan Lake Louise shuttle","Confirm reservation and parking instructions.","plan"),("21:00","Sleep","Mountain base.","rest"),("22:00","Sleep","Mountain base.","rest"),("23:00","Sleep","Mountain base.","rest")])
add("Day 7 · Yoho to Lake Louise cabin base", "2026-09-29", "Lake Louise", "Emerald Lake / Field → Takakkaw Falls if open → Lake Louise", "Move into the cabin base and keep the afternoon unhurried.", "Baker Creek, Storm Mountain or Paradise Lodge", [
("06:00","Cabin breakfast","Use kitchenette where available. Storm Mountain has no kitchen.","food"),("07:00","Emerald Lake sunrise option","Quiet lake walk if staying nearby.","explore"),("08:00","Check out","Pack layers for waterfall and lake weather.","travel"),("09:00","Takakkaw Falls option","Road and access must be open. Check Parks Canada.","explore"),("10:00","Takakkaw Falls","Short viewpoint experience.","explore"),("11:00","Field coffee / fuel","Small community stop.","food"),("12:00","Drive to Lake Louise","Short transfer.","travel"),("13:00","Lake Louise village lunch","Groceries for cabin breakfast and snacks.","food"),("14:00","Check-in cabin","Baker Creek / Storm Mountain / Paradise.","travel"),("15:00","Cabin reset","Fireplace, creek or lodge grounds.","rest"),("16:00","Bow Valley Parkway viewpoint","Morant's Curve if time and light allow.","explore"),("17:00","Return to cabin","Keep the evening easy.","travel"),("18:00","Dinner","Book Storm or Emerald dining ahead. Baker Creek has café options.","food"),("19:00","Cabin evening","Fire, cards, reading.","rest"),("20:00","Shuttle check","Reconfirm Moraine and Lake Louise shuttle times.","plan"),("21:00","Sleep","Early start tomorrow.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 8 · Lake Louise and Moraine Lake", "2026-09-30", "Lake Louise", "Reserved Parks Canada shuttle from Lake Louise Park and Ride", "One reservation day. Do both lakes only if the shuttle schedule makes it comfortable.", "Lake Louise", [
("06:00","Breakfast","Early breakfast and layers.","food"),("07:00","Drive to Park and Ride","Use the reservation instructions, not lakeshore parking.","travel"),("08:00","Lake Louise shuttle / access","Reservation time varies. Allow queue buffer.","travel"),("09:00","Lake Louise lakeshore","Lakeshore walk and photos.","explore"),("10:00","Lake Louise","Tea House hike only if weather, fitness and time support it.","explore"),("11:00","Lake Louise","Return to shuttle connection.","explore"),("12:00","Moraine Lake transfer","Use the reserved shuttle connection if booked.","travel"),("13:00","Moraine Lake","Rockpile viewpoint and lakeshore.","explore"),("14:00","Moraine Lake","Optional short trail only. Avoid an unplanned long hike.","explore"),("15:00","Return shuttle","Expect waiting time.","travel"),("16:00","Return to cabin","Hot drink and reset.","rest"),("17:00","Cabin evening","Fireplace / creek.","rest"),("18:00","Dinner","Cabin or reserved lodge dinner.","food"),("19:00","Dinner","Slow evening.","food"),("20:00","Pack for Icefields Parkway","Fill water, snacks, layers, fuel.","plan"),("21:00","Sleep","Tomorrow is a long scenic drive.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 9 · Icefields Parkway to Jasper", "2026-10-01", "Jasper", "Lake Louise → Bow Lake → Peyto Lake → Columbia Icefield → Athabasca Falls → Jasper", "Treat the Parkway as the day's attraction, not a transfer.", "Jasper town or operating lodge", [
("06:00","Breakfast + fuel","Pack lunch. Fuel before leaving Lake Louise.","food"),("07:00","Depart Lake Louise","Early light and wildlife awareness.","travel"),("08:00","Bow Lake","Short lakeshore viewpoint.","explore"),("09:00","Peyto Lake","Viewpoint and short walk. Weather dependent.","explore"),("10:00","Waterfowl Lakes / Mistaya","Choose a brief stop.","explore"),("11:00","Weeping Wall","Viewpoint and stretch.","stop"),("12:00","Columbia Icefield Discovery Centre","Lunch, fuel and attraction check.","food"),("13:00","Athabasca Glacier / Skywalk option","Only with pre-booked tour and suitable weather.","explore"),("14:00","Columbia Icefield","If no tour, use a short glacier viewpoint and continue.","explore"),("15:00","Sunwapta Falls","Short walk if open.","explore"),("16:00","Athabasca Falls","Powerful falls viewpoint.","explore"),("17:00","Drive to Jasper","Final leg, watch wildlife.","travel"),("18:00","Check-in","Jasper hotel / lodge.","travel"),("19:00","Dinner","Town dinner.","food"),("20:00","Rest","Confirm tomorrow's Jasper attractions.","rest"),("21:00","Sleep","Mountain day complete.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 10 · Jasper lakes and town", "2026-10-02", "Jasper", "Jasper town → Pyramid Lake → Maligne Road → Maligne Lake if open", "Keep closure-sensitive places as optional. Maligne Canyon and Edith Cavell Road remain closed in the 2026 bulletin.", "Jasper", [
("06:00","Breakfast","Check Parks Canada JasperNow / bulletins.","plan"),("07:00","Pyramid Lake","Sunrise or early lake walk.","explore"),("08:00","Patricia Lake","Short scenic loop.","explore"),("09:00","Jasper town","Coffee and supplies.","food"),("10:00","Maligne Road","Drive only after checking road and attraction status.","travel"),("11:00","Medicine Lake","Viewpoint and wildlife awareness.","explore"),("12:00","Maligne Lake option","Lunch / lake if open. Cruise requires advance booking and operating confirmation.","explore"),("13:00","Maligne Lake","Walk the shore or cruise if confirmed.","explore"),("14:00","Return toward Jasper","Build return buffer.","travel"),("15:00","Lac Beauvert","Easy late-afternoon lake option.","explore"),("16:00","Jasper town","Museum, shops or café.","explore"),("17:00","Rest","Prep for early Icefields Parkway return.","rest"),("18:00","Dinner","Jasper dinner.","food"),("19:00","Dinner","Slow evening.","food"),("20:00","Pack vehicle","Keep the next day comfortable.","plan"),("21:00","Sleep","Early start tomorrow.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 11 · Jasper to Banff", "2026-10-03", "Banff or Canmore", "Jasper → Athabasca Falls → Icefields Parkway → Lake Louise → Banff / Canmore", "Repeat the Parkway from a different direction. Stop less, enjoy more.", "Banff or Canmore", [
("06:00","Breakfast + fuel","Check 511 Alberta and Parks Canada.","plan"),("07:00","Depart Jasper","Early mountain drive.","travel"),("08:00","Athabasca Falls","Return stop if missed on Day 9.","explore"),("09:00","Sunwapta Falls","Optional second waterfall.","explore"),("10:00","Columbia Icefield","Coffee, fuel, weather decision.","stop"),("11:00","Parker Ridge / viewpoint option","Only if trail and weather are suitable.","explore"),("12:00","Packed lunch","Use a designated stop. Protect daylight.","food"),("13:00","Peyto / Bow Lake option","Pick one final major viewpoint.","explore"),("14:00","Drive to Lake Louise","Trans-Canada connection.","travel"),("15:00","Lake Louise village","Coffee / groceries.","stop"),("16:00","Drive to Banff or Canmore","Short final leg.","travel"),("17:00","Check-in","Hotel reset.","travel"),("18:00","Dinner","Banff Avenue or Canmore.","food"),("19:00","Dinner","Walkable evening.","food"),("20:00","Plan local day","Choose Banff or Canmore focus.","plan"),("21:00","Sleep","Overnight recovery.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 12 · Banff and Canmore", "2026-10-04", "Banff or Canmore", "Local Banff / Canmore loop", "A lower-mileage day after two major drives.", "Banff or Canmore", [
("06:00","Slow breakfast","No early transfer.","food"),("07:00","Bow Falls","Quiet morning viewpoint.","explore"),("08:00","Banff Avenue","Coffee and town walk.","explore"),("09:00","Banff town","Shops, galleries and visitor centre.","explore"),("10:00","Banff Gondola option","Book / check operating status and weather.","explore"),("11:00","Banff Gondola","Summit boardwalk if open.","explore"),("12:00","Lunch","Banff or summit restaurant.","food"),("13:00","Upper Hot Springs or rest","Choose one recovery activity.","rest"),("14:00","Upper Hot Springs / rest","Flexible.","rest"),("15:00","Drive to Canmore","Explore the town if staying there.","travel"),("16:00","Canmore arts / cafés","Slow local hour.","explore"),("17:00","Canmore / Banff","Return to hotel.","travel"),("18:00","Dinner","Final Rockies town dinner.","food"),("19:00","Dinner","Keep luggage simple.","food"),("20:00","Pack for return","Confirm Revelstoke and YVR stays.","plan"),("21:00","Sleep","Return leg begins tomorrow.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 13 · Banff to Revelstoke", "2026-10-05", "Revelstoke", "Banff / Canmore → Yoho → Golden → Rogers Pass → Revelstoke", "Use the Trans-Canada return leg with a few intentional stops.", "Revelstoke", [
("06:00","Breakfast + check-out","Pack for a 4 to 5 hour baseline drive.","travel"),("07:00","Depart Banff / Canmore","Fuel before the pass.","travel"),("08:00","Yoho / Field","Coffee or Emerald Lake if you missed it.","stop"),("09:00","Golden","Fuel and short break.","stop"),("10:00","Golden to Rogers Pass","Mountain drive.","travel"),("11:00","Rogers Pass","Short viewpoint / visitor centre if open.","explore"),("12:00","Rogers Pass lunch","Packed lunch or road stop.","food"),("13:00","Drive to Revelstoke","Final leg.","travel"),("14:00","Arrive Revelstoke","Check in early if possible.","travel"),("15:00","Revelstoke riverfront","Walk and coffee.","explore"),("16:00","Revelstoke town","Laundry / groceries / souvenirs.","explore"),("17:00","Rest","Protect the final long drive.","rest"),("18:00","Dinner","Early dinner.","food"),("19:00","Route and flight check","DriveBC, flight, rental return, baggage.","plan"),("20:00","Pack","Keep outlet purchases accessible.","plan"),("21:00","Sleep","Last road night.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 14 · Revelstoke to YVR", "2026-10-06", "Richmond / YVR", "Revelstoke → Kamloops / Hope → Vancouver / Richmond", "Long return day. Put the final night near YVR if the flight is before late evening.", "Richmond / YVR airport hotel", [
("06:00","Breakfast + check-out","Start early. Fuel before departure.","travel"),("07:00","Depart Revelstoke","Confirm DriveBC before leaving.","travel"),("08:00","Sicamous / Salmon Arm","Coffee and fuel buffer.","stop"),("09:00","Continue west","Do not add detours today.","travel"),("10:00","Kamloops area","Rest stop and fuel.","stop"),("11:00","Coquihalla / Highway 5","Weather and construction check.","travel"),("12:00","Lunch stop","Keep it fast but proper.","food"),("13:00","Continue toward Hope","Long transfer block.","travel"),("14:00","Hope / rest","Stretch and fuel.","stop"),("15:00","Fraser Valley to Vancouver","Traffic buffer begins.","travel"),("16:00","Vancouver / Richmond","Continue to hotel.","travel"),("17:00","YVR hotel check-in","Return rental car only if flight plan makes that sensible.","travel"),("18:00","Dinner near hotel","Do not cross the metro area.","food"),("19:00","Baggage sort","Keep outlet purchases within airline limits.","plan"),("20:00","Final outlet decision","If shopping is essential, move it to tomorrow only if flight time permits.","plan"),("21:00","Sleep","Early flight buffer.","rest"),("22:00","Sleep","Overnight recovery.","rest"),("23:00","Sleep","Overnight recovery.","rest")])
add("Day 15 · Outlet + departure", "2026-10-07", "YVR / departure", "YVR hotel → McArthurGlen → YVR departure", "Use the outlet only if the flight and luggage plan allow a genuine buffer.", "Departure", [
("06:00","Flight buffer","Check flight, terminal and rental-car status.","travel"),("07:00","Breakfast","Hotel breakfast / airport transfer.","food"),("08:00","Pack and check out","Leave luggage at confirmed hotel storage or in the car only briefly.","travel"),("09:00","Transfer to McArthurGlen","Canada Line or short drive.","travel"),("10:00","McArthurGlen final shop","Official plan-your-visit page for current hours. Keep a hard departure cutoff.","shop"),("11:00","Outlet final shop","Use luggage lockers only if confirmed available.","shop"),("12:00","Lunch / return to YVR","Do not add Tsawwassen or another mall.","food"),("13:00","YVR check-in","Baggage and tax-free / receipt tasks.","travel"),("14:00","Airport buffer","Security and immigration.","travel"),("15:00","Airport buffer","Flight time unknown. Keep open.","travel"),("16:00","Departure buffer","Do not book an attraction in this hour.","travel"),("17:00","Flight buffer","Adjust based on actual departure.","travel"),("18:00","Departure","Use actual flight time.","travel"),("19:00","Departure","Use actual flight time.","travel"),("20:00","Departure","Use actual flight time.","travel"),("21:00","Departure","Use actual flight time.","travel"),("22:00","Departure","Use actual flight time.","travel"),("23:00","Departure","Use actual flight time.","travel")])

route = [
 {"name":"Vancouver","date":"23 Sep","km":"city","stay":"Vancouver / Richmond","color":"#7dd3fc"},
 {"name":"Whistler","date":"25 Sep","km":"122 km from Vancouver","stay":"Whistler Village","color":"#a7f3d0"},
 {"name":"Kamloops","date":"26 Sep","km":"300 km from Whistler","stay":"Kamloops","color":"#fde68a"},
 {"name":"Revelstoke","date":"27 Sep","km":"213 km from Kamloops","stay":"Revelstoke","color":"#fdba74"},
 {"name":"Golden / Yoho","date":"28 Sep","km":"149 km from Revelstoke","stay":"Golden, Field or Emerald Lake","color":"#fca5a5"},
 {"name":"Lake Louise","date":"29 Sep","km":"short transfer from Yoho","stay":"Baker Creek / Storm / Paradise","color":"#c4b5fd"},
 {"name":"Jasper","date":"1 Oct","km":"340 km via Icefields Parkway","stay":"Jasper","color":"#93c5fd"},
 {"name":"Banff / Canmore","date":"3 Oct","km":"303 km from Jasper","stay":"Banff or Canmore","color":"#86efac"},
 {"name":"Revelstoke","date":"5 Oct","km":"284 km from Banff","stay":"Revelstoke","color":"#fdba74"},
 {"name":"YVR","date":"6 Oct","km":"566 km from Revelstoke","stay":"Richmond / YVR","color":"#f0abfc"},
 {"name":"Departure","date":"7 Oct","km":"airport day","stay":"flight","color":"#f9a8d4"},
]

payload = {
  "meta": {"title":"Canada Rockies · Vancouver loop", "start":"2026-09-23", "end":"2026-10-07", "travelers":2, "currency":"CAD", "assumption":"Exact flight times and booking inventory not supplied; all stays are candidates."},
  "route": route,
  "days": plans,
  "hotels": hotels,
  "activities": activities,
  "route_legs": [
    {"from":"Vancouver","to":"Whistler","distance":"122 km","time":"2.0 h baseline","note":"Sea-to-Sky Highway. Add stops."},
    {"from":"Whistler","to":"Kamloops","distance":"300 km","time":"4.8 h baseline","note":"Duffy Lake route is scenic and weather-sensitive."},
    {"from":"Kamloops","to":"Revelstoke","distance":"213 km","time":"2.9 h baseline","note":"Trans-Canada through Shuswap."},
    {"from":"Revelstoke","to":"Golden","distance":"149 km","time":"2.1 h baseline","note":"Rogers Pass / Glacier region."},
    {"from":"Golden","to":"Lake Louise","distance":"21 km baseline","time":"0.5 h baseline","note":"Yoho / Field detours make this a full day."},
    {"from":"Lake Louise","to":"Jasper","distance":"340 km","time":"5.3 h baseline","note":"Icefields Parkway is the attraction; allocate the full day."},
    {"from":"Jasper","to":"Banff","distance":"303 km","time":"4.7 h baseline","note":"Second full Parkway day with stops."},
    {"from":"Banff","to":"Revelstoke","distance":"284 km","time":"4.0 h baseline","note":"Return west on Trans-Canada."},
    {"from":"Revelstoke","to":"Vancouver","distance":"566 km","time":"7.1 h baseline","note":"Long transfer. Final night near YVR recommended."}
  ],
  "sources": [
    {"id":1,"label":"Banff planning","url":"https://parks.canada.ca/pn-np/ab/banff/visit"},
    {"id":2,"label":"Lake Louise and Moraine access","url":"https://parks.canada.ca/pn-np/ab/banff/visit/parkbus/louise"},
    {"id":3,"label":"Yoho planning","url":"https://parks.canada.ca/pn-np/bc/yoho/visit"},
    {"id":4,"label":"Jasper planning","url":"https://parks.canada.ca/pn-np/ab/jasper/visit"},
    {"id":5,"label":"Jasper 2026 bulletin","url":"https://parks.canada.ca/pn-np/ab/jasper/bulletins/76ECAE58-8A63-480C-8304-DC903837EEFD"},
    {"id":6,"label":"McArthurGlen plan your visit","url":"https://www.mcarthurglen.com/en/outlets/ca/designer-outlet-vancouver/plan-your-visit"},
    {"id":7,"label":"Baker Creek","url":"https://www.basecampresorts.com/bakercreek"},
    {"id":8,"label":"Storm Mountain Lodge","url":"https://stormmountainlodge.com/logcabins"},
    {"id":9,"label":"Emerald Lake Lodge","url":"https://crmr.com/resorts/emerald-lake/accommodations/"},
    {"id":10,"label":"Paradise Lodge","url":"https://www.paradiselodge.com/"},
    {"id":11,"label":"The Juniper","url":"https://thejuniper.com/"},
    {"id":12,"label":"Tourism Jasper stays","url":"https://jasper.travel/accommodations"},
    {"id":13,"label":"Canmore stays","url":"https://www.explorecanmore.ca/all-accommodations"},
    {"id":14,"label":"Tourism Whistler activities","url":"https://www.whistler.com/activities/"},
    {"id":15,"label":"Icefields Parkway stops","url":"https://icefieldsparkway.com/things-to-do-see/popular-stops-along-the-way"},
    {"id":16,"label":"DriveBC","url":"https://www.drivebc.ca/"},
    {"id":17,"label":"511 Alberta","url":"https://511.alberta.ca/"},
    {"id":18,"label":"Parks Canada advisories","url":"https://parks.canada.ca/voyage-travel/advisories"}
  ]
}

DATA.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"wrote {DATA} with {len(plans)} days and {sum(len(d['blocks']) for d in plans)} hourly blocks")
